services:
  app:
    build: .
    container_name: frankenphp
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - /home/sample-docker/app/laravel:/app
      - /home/sample-docker/app/Caddyfile:/etc/caddy/Caddyfile
      - /home/sample-docker/app/.bashrc:/root/.bashrc
      - /home/sample-docker/app/php.ini:/usr/local/etc/php/php.ini
    environment:
      # 도메인만 적으면 자동으로 HTTPS(Let's Encrypt)가 적용됩니다.
      - SERVER_NAME=gwanghoon.shop
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dev_db
    volumes:
      - /home/sample-docker/db/var/lib/mysql:/var/lib/mysql
    restart: unless-stopped
